"use client";

import React, { useState } from "react";

export default function SingleBlogPage() {
  const [commentData, setCommentData] = useState({
    comment: "",
    name: "",
    email: "",
    website: "",
    saveInfo: false,
  });

  const handleCommentSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("Comment Data Submitted:", commentData);
    // Process comment logic here
  };

  return (
    <div className="bg-white min-h-screen text-[#011c2b] font-sans antialiased selection:bg-green-100">
      {/* ================= MAIN CONTENT AREA ================= */}
      <main className="max-w-4xl mx-auto px-4 py-12 sm:px-6 md:py-20 flex flex-col gap-8">
        {/* Post Primary Feature Image Card */}
        <div
          className="w-full h-56 sm:h-96 md:h-112.5 rounded-2xl bg-cover bg-center shadow-md border border-gray-100"
          style={{ backgroundImage: "url('/images/blogs/post-1.jpg')" }} // Replace with actual image path
        />

        {/* Article Body Content */}
        <article className="prose prose-gray max-w-none text-sm sm:text-base text-gray-600 leading-relaxed flex flex-col gap-6">
          <p>
            Switching to solar energy is one of the smartest decisions
            homeowners can make today. With rising electricity costs & growing
            environmental concerns, solar power offers a clean, reliable, and
            cost-effective solution. This guide will walk you through everything
            you need to know about solar energy from how it works to how you can
            benefit from it in your daily life.
          </p>
          <p>
            Solar energy is generated by capturing sunlight using solar panels
            and converting it into usable electricity. These panels produce
            direct current (DC) power, which is then converted into alternating
            current (AC) power by an inverter so it can be used in your home.
            Any excess energy can be sent back to the grid or stored in
            batteries for later use.
          </p>

          {/* Styled Pull Quote */}
          <blockquote className="my-4 bg-[#f4f7f9] border-l-4 border-[#4caf50] rounded-r-xl p-5 sm:p-6 not-italic flex items-start gap-4">
            <span className="text-[#4caf50] text-4xl font-serif leading-none select-none shrink-0">
              “
            </span>
            <div>
              <p className="text-[#011c2b] text-sm sm:text-base font-bold leading-snug">
                Harnessing the power of the sun not only helps you save on
                electricity bills but also contributes to a cleaner environment,
                greater energy independence, and a more sustainable future for
                your home and family.
              </p>
            </div>
          </blockquote>

          <p>
            Solar power helps reduce your monthly electricity bills, protects
            you from rising energy prices, and lowers your carbon footprint. It
            also increases your energy independence and can add long-term value
            to your property. With battery storage, you can even keep your home
            powered during outages.
          </p>

          {/* Subheading Title Section */}
          <h2 className="text-[#011c2b] text-xl sm:text-2xl font-extrabold tracking-tight mt-4 mb-2">
            Understanding installation and costs
          </h2>
          <p>
            The installation process usually includes site inspection, system
            design, engineering, installation, and final testing. While the
            upfront cost may seem significant, solar systems typically pay for
            themselves over time through energy savings and incentives, making
            them a smart long-term investment.
          </p>

          {/* List Content */}
          <ul className="list-none flex flex-col gap-3 pl-1 mt-2">
            {[
              "While there is an upfront investment, long-term savings on electricity bills & possible incentives help recover costs over time.",
              "Professional technicians install the system, connect all components & test performance to ensure everything works safely & efficiently.",
              "Necessary permits, grid approvals, and paperwork are handled to ensure a smooth and compliant installation process.",
              "Based on the assessment a customized system is designed & transparent cost estimate is provided with no hidden charges.",
              "A detailed inspection of your property & energy usage helps determine the right system size, layout & expected performance.",
            ].map((text, idx) => (
              <li
                key={idx}
                className="flex items-start gap-2.5 text-xs sm:text-sm"
              >
                <span className="text-[#4caf50] shrink-0 font-bold mt-0.5">
                  •
                </span>
                <span>{text}</span>
              </li>
            ))}
          </ul>

          <p className="mt-2">
            One of the most effective ways to lower your carbon footprint is by
            reducing energy consumption. Simple steps like using
            energy-efficient appliances, switching to LED lighting, and turning
            off devices when not in use can significantly cut down on emissions.
            Choosing renewable energy sources, where available, further helps
            minimize dependence on fossil fuels and supports cleaner power
            generation.
          </p>
        </article>

        {/* Meta Utility Footer: Tags & Share Actions */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-y border-gray-100 py-6 my-4">
          {/* Left: Interactive Tags */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[#011c2b] text-xs font-bold mr-1">Tags:</span>
            {["Green Energy", "Solar Energy", "Sustainable Energy"].map(
              (tag, idx) => (
                <span
                  key={idx}
                  className="bg-[#4caf50] hover:bg-[#43a047] text-white text-xs font-medium px-3 py-1 rounded transition-colors cursor-pointer"
                >
                  {tag}
                </span>
              ),
            )}
          </div>

          {/* Right: Mock Social Share Links */}
          <div className="flex items-center gap-2">
            {["f", "t", "in"].map((social, idx) => (
              <button
                key={idx}
                className="w-8 h-8 rounded bg-[#4caf50] hover:bg-[#43a047] text-white text-xs font-bold flex items-center justify-center transition-colors uppercase"
                aria-label={`Share on ${social}`}
              >
                {social}
              </button>
            ))}
          </div>
        </div>

        {/* ================= COMMENT FORM SECTION ================= */}
        <section className="mt-4">
          <h3 className="text-[#011c2b] text-xl font-bold tracking-tight mb-1">
            Leave a Reply
          </h3>
          <p className="text-gray-400 text-xs mb-6">
            Your email address will not be published. Required fields are marked
            *
          </p>

          <form onSubmit={handleCommentSubmit} className="flex flex-col gap-4">
            {/* Row 1: Big Comment Box */}
            <div className="flex flex-col gap-2">
              <label className="text-[#011c2b] text-xs font-bold tracking-wide">
                Comment *
              </label>
              <textarea
                rows={6}
                required
                className="w-full bg-[#f4f7f9] rounded-xl px-4 py-3 border-none outline-none focus:ring-2 focus:ring-[#4caf50] text-sm text-[#011c2b] transition-all resize-none"
                value={commentData.comment}
                onChange={(e) =>
                  setCommentData({ ...commentData, comment: e.target.value })
                }
              />
            </div>

            {/* Row 2: User Particulars */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="flex flex-col gap-2">
                <label className="text-[#011c2b] text-xs font-bold tracking-wide">
                  Name *
                </label>
                <input
                  type="text"
                  required
                  className="w-full bg-[#f4f7f9] rounded-xl px-4 py-3 border-none outline-none focus:ring-2 focus:ring-[#4caf50] text-sm text-[#011c2b] transition-all"
                  value={commentData.name}
                  onChange={(e) =>
                    setCommentData({ ...commentData, name: e.target.value })
                  }
                />
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-[#011c2b] text-xs font-bold tracking-wide">
                  Email *
                </label>
                <input
                  type="email"
                  required
                  className="w-full bg-[#f4f7f9] rounded-xl px-4 py-3 border-none outline-none focus:ring-2 focus:ring-[#4caf50] text-sm text-[#011c2b] transition-all"
                  value={commentData.email}
                  onChange={(e) =>
                    setCommentData({ ...commentData, email: e.target.value })
                  }
                />
              </div>
              <div className="flex flex-col gap-2">
                <label className="text-[#011c2b] text-xs font-bold tracking-wide">
                  Website
                </label>
                <input
                  type="url"
                  className="w-full bg-[#f4f7f9] rounded-xl px-4 py-3 border-none outline-none focus:ring-2 focus:ring-[#4caf50] text-sm text-[#011c2b] transition-all"
                  value={commentData.website}
                  onChange={(e) =>
                    setCommentData({ ...commentData, website: e.target.value })
                  }
                />
              </div>
            </div>

            {/* Checkbox */}
            <div className="flex items-start gap-2.5 mt-2">
              <input
                id="saveInfo"
                type="checkbox"
                className="w-4 h-4 rounded text-[#4caf50] focus:ring-[#4caf50] border-gray-300 mt-0.5 accent-[#4caf50] cursor-pointer"
                checked={commentData.saveInfo}
                onChange={(e) =>
                  setCommentData({ ...commentData, saveInfo: e.target.checked })
                }
              />
              <label
                htmlFor="saveInfo"
                className="text-gray-500 text-xs select-none cursor-pointer leading-normal"
              >
                Save my name, email, and website in this browser for the next
                time I comment.
              </label>
            </div>

            {/* Post button wrapper */}
            <div className="mt-4">
              <button
                type="submit"
                className="bg-[#4caf50] hover:bg-[#43a047] text-white font-bold text-xs uppercase tracking-wider px-6 py-3.5 rounded-lg shadow-sm transition-colors duration-150"
              >
                Post Comment
              </button>
            </div>
          </form>
        </section>
      </main>
    </div>
  );
}
