import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/db";
import { saveImage, deleteImage } from "@/lib/imageHelper";

type Blog = {
  id: number;
  title: string;
  category: string;
  imageUrl: string;
  slug: string;
  content: string;
  tags: string[];
  date: string;
  createdAt?: Date;
};

const DEFAULT_BLOGS: Blog[] = [
  {
    id: 1,
    title: "A Complete Guide to Solar Energy for Homeowners",
    category: "Residential Solar",
    imageUrl: "/images/blogs/post-1.jpg",
    slug: "a-complete-guide-to-solar-energy-for-homeowners",
    content: "Switching to solar energy is one of the smartest decisions homeowners can make today. With rising electricity costs & growing environmental concerns, solar power offers a clean, reliable, and cost-effective solution.",
    tags: ["Green Energy", "Solar Energy", "Sustainable Energy"],
    date: "Jun 28, 2026",
  },
  {
    id: 2,
    title: "Top Benefits of Switching to Solar Power in 2026",
    category: "Solar Benefits",
    imageUrl: "/images/blogs/post-2.jpg",
    slug: "top-benefits-of-switching-to-solar-power-in-2026",
    content: "Harnessing the power of the sun not only helps you save on electricity bills but also contributes to a cleaner environment, greater energy independence, and a more sustainable future for your home and family.",
    tags: ["Savings", "Clean Energy", "Solar Benefits"],
    date: "Jun 28, 2026",
  },
  {
    id: 3,
    title: "How Solar Panels Work: A Simple Guide for Homeowners",
    category: "Installation Guide",
    imageUrl: "/images/blogs/post-3.jpg",
    slug: "how-solar-panels-work-a-simple-guide-for-homeowners",
    content: "Solar energy is generated by capturing sunlight using solar panels and converting it into usable electricity. These panels produce direct current (DC) power, which is then converted into alternating current (AC) power.",
    tags: ["Tech", "DIY", "Solar Basics"],
    date: "Jun 27, 2026",
  },
  {
    id: 4,
    title: "Solar Installation Process Explained Step by Step",
    category: "Solar Panels",
    imageUrl: "/images/blogs/post-4.jpg",
    slug: "solar-installation-process-explained-step-by-step",
    content: "The installation process usually includes site inspection, system design, engineering, installation, and final testing. While the upfront cost may seem significant, systems typically pay for themselves.",
    tags: ["Installation", "Expert Advice", "Solar Panels"],
    date: "Jun 27, 2026",
  },
  {
    id: 5,
    title: "Residential vs Commercial Solar: Which Is Right for You?",
    category: "Energy Solutions",
    imageUrl: "/images/blogs/post-5.jpg",
    slug: "residential-vs-commercial-solar-which-is-right-for-you",
    content: "Residential and commercial systems differ in scale, cost, structural setups, and financing. This detailed analysis compares performance metrics, roof design requirements, and payback periods.",
    tags: ["Commercial Solar", "Residential Solar", "Analysis"],
    date: "Jun 26, 2026",
  },
  {
    id: 6,
    title: "How to Maintain Your Solar System for Peak Performance",
    category: "Solar Maintenance",
    imageUrl: "/images/blogs/post-6.jpg",
    slug: "how-to-maintain-your-solar-system-for-peak-performance",
    content: "One of the most effective ways to ensure solar system longevity is regular checkups. Maintain clean surfaces, look out for shadows, and monitor the inverter performance logging data regularly.",
    tags: ["Maintenance", "Tips", "Lifespan"],
    date: "Jun 26, 2026",
  },
];

export async function GET() {
  try {
    const { db } = await connectToDatabase();
    let blogs = await db.collection("blogs").find({}).toArray();
    if (blogs.length === 0) {
      await db.collection("blogs").insertMany(DEFAULT_BLOGS);
      blogs = await db.collection("blogs").find({}).toArray();
    }
    return NextResponse.json({ success: true, data: blogs });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { db } = await connectToDatabase();
    
    const allBlogs = (await db.collection("blogs").find({}).toArray()) as unknown as Blog[];
    const nextId = allBlogs.length > 0 ? Math.max(...allBlogs.map((b: Blog) => b.id)) + 1 : 1;
    
    const savedImagePath = saveImage(body.imageUrl, "blogs", nextId);
    
    const newBlog = {
      ...body,
      imageUrl: savedImagePath,
      id: nextId,
      createdAt: new Date(),
    };
    
    await db.collection("blogs").insertOne(newBlog);
    return NextResponse.json({ success: true, data: newBlog });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const { id, ...updateData } = body;
    const { db } = await connectToDatabase();
    
    const existing = await db.collection("blogs").findOne({ id: Number(id) });
    if (existing) {
      if (updateData.imageUrl && updateData.imageUrl !== existing.imageUrl) {
        updateData.imageUrl = saveImage(updateData.imageUrl, "blogs", id);
        deleteImage(existing.imageUrl);
      }
    }
    
    await db.collection("blogs").updateOne({ id: Number(id) }, { $set: updateData });
    return NextResponse.json({ success: true, data: { id, ...updateData } });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function DELETE(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");
    if (!id) {
      return NextResponse.json({ success: false, error: "Missing ID parameter" }, { status: 400 });
    }
    const { db } = await connectToDatabase();
    
    const existing = await db.collection("blogs").findOne({ id: Number(id) });
    if (existing) {
      deleteImage(existing.imageUrl);
    }
    
    await db.collection("blogs").deleteOne({ id: Number(id) });
    return NextResponse.json({ success: true });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
